# Generated by Django 5.2.3 on 2026-02-15 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('orders', '0003_order_billing_address_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='billings_orders', to='addresses.address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_orders', to='addresses.address'),
        ),
    ]
